VARIABLE LABELS
 start 'start'
 /end 'end'
 /_1_Acknowledge '1. Acknowledge'
 /_2_Please_sign_the_consent_form '2. Please sign the consent form'
 /_3_Hello_Welcome '3. Hello & Welcome. '
 /_4_Institution_Name '4. Institution Name'
 /Institution_Type '5. Institution Type'
 /_6_Elaborate_if_othe_type_of_Institution '6. Elaborate if other type of Institution'
 /_7_SECTION_1_DEMOGRAPHICS_SERVICES '7. SECTION 1: DEMOGRAPHICS & SERVICES'
 /Which_regions_do_you_predomina '8. Which Eastern regions do you predominantly serve?'
 /Which_regions_do_you_predomina_lower_eastern_region '8. Which Eastern regions do you predominantly serve? :: Lower Eastern Region '
 /Which_regions_do_you_predomina_upper_eastern_region '8. Which Eastern regions do you predominantly serve? :: Upper Eastern Region'
 /Which_regions_do_you_predomina_north_eastern_region '8. Which Eastern regions do you predominantly serve? :: North Eastern Region'
 /Which_regions_do_you_predomina_other '8. Which Eastern regions do you predominantly serve? :: Other'
 /Which_regions_do_you_predomina_all_the_above '8. Which Eastern regions do you predominantly serve? :: All the Above'
 /_9_Elaborate_on_specific_count '9. Elaborate on specific counties of operation'
 /_9_Elaborate_on_specific_count_embu '9. Elaborate on specific counties of operation :: Embu'
 /_9_Elaborate_on_specific_count_isiolo '9. Elaborate on specific counties of operation :: Isiolo'
 /_9_Elaborate_on_specific_count_kirinyaga '9. Elaborate on specific counties of operation :: Kirinyaga'
 /_9_Elaborate_on_specific_count_kitui '9. Elaborate on specific counties of operation :: Kitui'
 /_9_Elaborate_on_specific_count_machakos '9. Elaborate on specific counties of operation :: Machakos'
 /_9_Elaborate_on_specific_count_makueni '9. Elaborate on specific counties of operation :: Makueni'
 /_9_Elaborate_on_specific_count_meru '9. Elaborate on specific counties of operation :: Meru'
 /_9_Elaborate_on_specific_count_tharaka_nithi '9. Elaborate on specific counties of operation :: Tharaka-Nithi'
 /_10_Specific_areas_served_in_Embu_County '10. Specific areas served in Embu County'
 /_10a_Specific_areas_ved_in_Isiolo_County '10a. Specific areas served in Isiolo County'
 /_10b_Specific_areas_in_Kirinyaga_County '10b. Specific areas served in Kirinyaga County'
 /_10c_Specific_areas_rved_in_Kitui_County '10c. Specific areas served in Kitui County'
 /_10d_Specific_areas_d_in_Machakos_County '10d. Specific areas served in Machakos County'
 /_10e_Specific_areas_ed_in_Makueni_County '10e. Specific areas served in Makueni County'
 /_10e_Specific_areas_erved_in_Meru_County '10e. Specific areas served in Meru County'
 /_10f_Specific_areas_Tharaka_Nithi_County '10f. Specific areas served in Tharaka-Nithi County'
 /Do_you_provide_any_economic_se '11. Do you provide any economic services or opportunities?'
 /What_type_of_economic_services '12. Who are the beneficiaries of your economic services or opportunities that your institution primarily provide?'
 /What_type_of_economic_services_individual '12. Who are the beneficiaries of your economic services or opportunities that your institution primarily provide? :: Individuals'
 /What_type_of_economic_services__group '12. Who are the beneficiaries of your economic services or opportunities that your institution primarily provide? :: Groups'
 /What_type_of_economic_services_organization '12. Who are the beneficiaries of your economic services or opportunities that your institution primarily provide? :: Organizations'
 /What_type_of_economic_services_other '12. Who are the beneficiaries of your economic services or opportunities that your institution primarily provide? :: Other'
 /_13_Please_elaborate_er_beneficiaries_are '13. Please elaborate who the other beneficiaries are'
 /_14_What_age_does_yo_eficiaries_belong_to '14. What age does your clients/beneficiaries belong to?'
 /_14_What_age_does_yo_eficiaries_belong_to_kids_below_18yrs '14. What age does your clients/beneficiaries belong to? :: Below 18yrs'
 /_14_What_age_does_yo_eficiaries_belong_to_youth_18_35_yrs '14. What age does your clients/beneficiaries belong to? :: Youth 18-35 Yrs'
 /_14_What_age_does_yo_eficiaries_belong_to_adults_36 '14. What age does your clients/beneficiaries belong to? :: Adults 36+'
 /_14_What_age_does_yo_eficiaries_belong_to_other '14. What age does your clients/beneficiaries belong to? :: Nascent institutions (Start-ups)'
 /_14_What_age_does_yo_eficiaries_belong_to_established_institutions '14. What age does your clients/beneficiaries belong to? :: Established institutions'
 /_14_What_age_does_yo_eficiaries_belong_to_does_not_matter '14. What age does your clients/beneficiaries belong to? :: Does not matter'
 /_15_What_Gender_does_es_Clients_belong_to '15. What Gender does your beneficiaries/Clients belong to?'
 /_15_What_Gender_does_es_Clients_belong_to_males '15. What Gender does your beneficiaries/Clients belong to? :: Male'
 /_15_What_Gender_does_es_Clients_belong_to_female '15. What Gender does your beneficiaries/Clients belong to? :: Female'
 /_15_What_Gender_does_es_Clients_belong_to_intersex '15. What Gender does your beneficiaries/Clients belong to? :: Intersex'
 /_15_What_Gender_does_es_Clients_belong_to_transgender '15. What Gender does your beneficiaries/Clients belong to? :: Transgender'
 /_15_What_Gender_does_es_Clients_belong_to_does_not_matter '15. What Gender does your beneficiaries/Clients belong to? :: Does not matter'
 /_16_SECTION_2_FINANCIAL_OFFERINGS '16. SECTION 2: FINANCIAL OFFERINGS'
 /_17_What_financing_o_programs_or_sources '17. What financing or funding options does your institution offer for economic initiatives? Please specify any unique programs or sources.'
 /_18_From_your_perspe_or_economic_projects '18. From your perspective, what are the major challenges faced by individuals or groups in accessing financing or funding for economic projects?'
 /Are_there_any_undisclosed_or_i '19. Are there any undisclosed or indirect costs associated with the financing options provided by your institution?'
 /_20_If_Yes_which_ones '20. If Yes, which ones?'
 /_21_SECTION_3_INCLU_VITY_ACCESSIBILITY '21. SECTION 3: INCLUSIVITY & ACCESSIBILITY'
 /Do_you_have_special_services_f '22. Do you have special services for marginalized groups e.g women, youths etc'
 /_23_Indicate_service_marginalized_groups '23. Indicate services offered for marginalized groups'
 /_24_In_what_ways_doe_within_the_community '24. In what ways does your institution ensure accessibility of services within the community?'
 /_25_SECTION_4_EDUCA_N_SUPPORT_PROGRAMS '25. SECTION 4: EDUCATION & SUPPORT PROGRAMS'
 /Does_your_institution_provide_ '26. Does your institution provide educational programs or workshops regarding legal business environments or statutory compliance required for conducting business in Kenya?'
 /_27_If_yes_elaborat_ng_business_in_Kenya '27. If yes, elaborate on the available educational programs or workshops regarding legal business environments or statutory compliance required for conducting business in Kenya'
 /_28_Bronchure_contai_by_your_institution '28. Bronchure containing products and services rendered by your institution'
 /_29_Bronchure_contai_by_your_institution '29. Bronchure containing products and services rendered by your institution'
 /_30_Bronchure_contai_by_your_institution '30. Bronchure containing products and services rendered by your institution'
 /_31_DEFINITION_Cont_buying_the_products '31. DEFINITION: Contract farming > You have a farm, a company signs a contact with you to produce for them, they incur production cost, they guarantee monopoly market, they deduct their cost of production w'
 + 'hile buying the products'
 /_32_Would_your_insti_economic_initiatives '32. Would your institution consider offering educational programs on lesser-known economic models, such as contract farming, to support economic initiatives?'
 /_33_SECTION_5_COLLA_RATIONS_NETWORKING '33. SECTION 5: COLLABORATIONS & NETWORKING'
 /_34_Has_your_institu_s_and_their_outcomes '34. Has your institution engaged in partnerships or collaborations with other economic actors for supporting economic projects? If so, could you describe these collaborations and their outcomes?'
 /_35_Could_your_insti_ons_and_partnerships '35. Could your institution provide contact information for potential case studies or further information on successful collaborations and partnerships?'
 /_36_How_readily_avai_e_within_your_region '36. How readily available is published information about your institution''s economic programs or opportunities for reference within your region?'
 /_37_What_additional_economic_initiatives '37. What additional resources or support (grants, loans, training programs, etc.) do you believe could significantly enhance the impact of your institution''s economic initiatives?'
 /_38_SECTION_6_SOCIAL_MEDIA_OUTREACH '38. SECTION 6: SOCIAL MEDIA & OUTREACH'
 /_39_How_open_is_your_onomic_opportunities '39. How open is your institution to utilizing social media platforms to disseminate information or resources related to economic opportunities?'
 /_40_Do_you_see_poten_iatives_or_resources '40. Do you see potential value in leveraging social media channels to reach a broader audience and promote economic initiatives or resources?'
 /_41_Lastly_are_ther_ment_and_empowerment '41. Lastly, are there any concerns or challenges your institution anticipates or experiences when participating in projects related to economic development and empowerment?'
 /_42_Thankyou '42. Thankyou '
 /_id '_id'
 /_uuid '_uuid'
 /_submission_time '_submission_time'
 /_validation_status '_validation_status'
 /_notes '_notes'
 /_status '_status'
 /_submitted_by '_submitted_by'
 /__version__ '__version__'
 /_tags '_tags'
 .
VALUE LABELS
 Institution_Type
 'chamas_self_help_groups' 'Chamas/Self Help Groups'
 'bank' 'Bank'
 'asset_financing' 'Asset financing'
 'sacco' 'SACCO'
 'digital_lender' 'Digital Lender'
 'insurance_for_business' 'Insurance for Business'
 'donors' 'Donors'
 'national_government_agency__yo' 'National government agency (Youth Fund, Women Fund, CDF, NGAF)'
 'fellowships_and_scholarships' 'Fellowships and scholarships'
 'other' 'Other'
 /Do_you_provide_any_economic_se
 'yes' 'Yes'
 'no' 'No'
 /Are_there_any_undisclosed_or_i
 'yes' 'Yes'
 'no' 'No'
 'prefer_not_to_say' 'Prefer not to say'
 /Do_you_have_special_services_f
 'yes' 'Yes'
 'no' 'No'
 /Does_your_institution_provide_
 'yes' 'Yes'
 'no' 'No'
 .